<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pview</string>
	</array>
	<key>name</key>
	<string>Pebble View</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>closing brace</string>
			<key>match</key>
			<string>\]</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(view)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the view element</string>
			<key>end</key>
			<string>(\[)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(subview)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the subview element</string>
			<key>end</key>
			<string>(;|\n|\[)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hidden</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(layer)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the layer element</string>
			<key>end</key>
			<string>(;|\n|\[)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dimensions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hidden</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(bitmap)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the bitmap element</string>
			<key>end</key>
			<string>(;|\n)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#resourceid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dimensions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hidden</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(font)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the font element</string>
			<key>end</key>
			<string>(;|\n)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#resourceid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(inverter)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the inverter element</string>
			<key>end</key>
			<string>(;|\n)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dimensions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hidden</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*?(text)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>matches a the text element</string>
			<key>end</key>
			<string>(;|\n)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dimensions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#using_font</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hidden</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>\s*#.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>color</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>foreground and optional background definition</string>
			<key>match</key>
			<string>(?&lt;=\s)(black|white|clear)(?:\s+(on)\s+(black|white|clear))?(?=\s|;)</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<key>dimensions</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string></string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string></string>
					<key>match</key>
					<string>\s*(width:)(\d+)(?=\s)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string></string>
					<key>match</key>
					<string>\s*(height:)(\d+)(?=\s)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string></string>
					<key>match</key>
					<string>\s*(top:)(-?\d+)(?=\s)</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>comment</key>
					<string></string>
					<key>match</key>
					<string>\s*(left:)(-?\d+)(?=\s|\))</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</array>
		</dict>
		<key>hidden</key>
		<dict>
			<key>comment</key>
			<string>optional keyword that indicates, that a element should be created in a hidden state.</string>
			<key>match</key>
			<string>(?&lt;=\s)hidden(?=\s|;)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>id</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(as)\s+('[a-zA-Z][a-zA-Z0-9_]*')(?=\s|;)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)('[a-zA-Z][a-zA-Z0-9_]*')(?=\s)</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)(with parameters)\s+\(([^\)]*?)\)(?=\s)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>resourceid</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)[A-Z][A-Z0-9_]*\s+</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<key>string</key>
		<dict>
			<key>match</key>
			<string>"([^"]|\")*?"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>using_font</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>font selection</string>
			<key>match</key>
			<string>(using font)\s+('[a-zA-Z][a-zA-Z0-9_]*')(?=\s|;)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>comment</key>
			<string>first class syntax element</string>
			<key>match</key>
			<string>(?&lt;=\s)\$[a-zA-Z][a-zA-Z0-9_]*?((-&gt;|.)[a-zA-Z][a-zA-Z0-9_]*)?(?=\s)</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pview</string>
	<key>uuid</key>
	<string>518cc445-c0b0-494e-8ca0-9c3475b7eab6</string>
</dict>
</plist>
